name: Deploy TWOBEONE App
on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Dispatch reason'
        required: false
        default: 'NA'
jobs:
  deploy:
    environment: twobeone-app
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22.19.0
      - name: Build
        env:
          MONGODB_URI: ${{secrets.MONGODB_URI}}
          MONGODB_DB_NAME: ${{secrets.MONGODB_DB_NAME}}
          PUBLIC_MODE: PROD
          CLOUDFLARE_ACCOUNT_ID: ${{secrets.CLOUDFLARE_ACCOUNT_ID}}
          CLOUDFLARE_IMAGES_API_TOKEN: ${{secrets.CLOUDFLARE_IMAGES_API_TOKEN}}
        run: |
          npm install
          CLOUDFLARE_DEPLOY=1 npm run build
      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy .svelte-kit/cloudflare --project-name=twobeone
